name: CI CD TB Infra

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -user: actions/checkcout@v3

      -name: Build test
       run: echo "Build sukses"

      -name: Deploy test
      run: echo "Deploy otomatis berhasil" name: CI CD TB Infra

 on:
 push:
 branches: [ main ]

 jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v3

 - name: Test build
 run: echo "Build sukses"

 - name: Deploy
 run: echo "Deploy otomatis berhasil"
